package com.example.poultryfarmmanager.ui.theme

import androidx.compose.runtime.compositionLocalOf

data class AppStrings(
    // Nav
    val navHome: String, val navBirds: String, val navEggs: String,
    val navFeed: String, val navHealth: String, val navTasks: String,
    // Common
    val save: String, val cancel: String, val edit: String, val delete: String,
    val notesOptional: String, val descriptionOptional: String,
    // Dashboard
    val dashboardTitle: String, val totalRevenue: String, val timeRange: String,
    val eggProductionDaily: String, val eggProductionWeekly: String,
    val birdInventory: String, val feedSummary: String, val quickActions: String,
    val logEggs: String, val addBirds: String, val addFeed: String, val addTask: String,
    val upload: String, val download: String,
    val eggsCollected: String, val totalPrefix: String,
    val totalCost: String, val feedTypes: String, val lowStock: String,
    val eggSales: String, val birdSales: String,
    val birdsLabel: String, val eggsLabel: String, val tasksLabel: String, val feedLabel: String,
    val syncing: String, val syncSuccess: String, val syncError: String,
    // Birds
    val birdInventoryTitle: String, val addBatch: String, val noBirds: String,
    val editBirdBatch: String, val addBirdBatch: String,
    val breed: String, val totalQuantity: String, val pricePerBird: String,
    val birdLeft: String, val birdSold: String, val birdSlaughtered: String,
    val revenuePrefix: String,
    // Eggs
    val eggProductionTitle: String, val noEggs: String, val todayProduction: String,
    val eggsUnit: String, val consumed: String, val remaining: String, val revenue: String,
    val logEggProduction: String, val totalEggsCollected: String,
    val eggsSold: String, val pricePerEgg: String, val eggsConsumed: String,
    // Feed
    val feedManagementTitle: String, val addFeedLabel: String, val noFeed: String,
    val feedLowSingular: String, val feedLowPlural: String,
    val lastRestocked: String, val lowStockBadge: String,
    val feedType: String, val quantityKg: String, val lowStockAlertKg: String,
    val useFeed: String, val howMuchUsed: String,
    // Tasks
    val tasksTitle: String, val addTaskLabel: String, val noTasks: String,
    val overdue: String, val due: String,
    val editTask: String, val addTaskTitle: String, val taskTitle: String, val dueDate: String,
    // Health
    val healthTitle: String, val addRecord: String, val noHealth: String,
    val records: String, val vaccines: String, val medications: String,
    val typeVaccine: String, val typeMedication: String, val typeDewormer: String,
    val typeSupplement: String, val typeOther: String,
    val nameHint: String, val date: String, val costOptional: String,
    val dosageOptional: String, val birdsTreatedOptional: String,
    val editHealthRecord: String, val addHealthRecord: String,
    val birdsSuffix: String, val dosagePrefix: String,
    val typeLabel: String,
    // Setup
    val appTagline: String, val connectYourFarm: String, val connectDescription: String,
    val farmCode: String, val farmCodePlaceholder: String, val farmCodeSupporting: String,
    val joinFarm: String, val shareCode: String,
)

val SwahiliStrings = AppStrings(
    navHome = "Nyumbani", navBirds = "Kuku", navEggs = "Mayai",
    navFeed = "Chakula", navHealth = "Afya", navTasks = "Kazi",
    save = "Hifadhi", cancel = "Ghairi", edit = "Hariri", delete = "Futa",
    notesOptional = "Maelezo (hiari)", descriptionOptional = "Maelezo (hiari)",
    dashboardTitle = "Dashibodi ya Shamba", totalRevenue = "Mapato Yote",
    timeRange = "Kipindi cha Wakati",
    eggProductionDaily = "Uzalishaji wa Mayai — Kila Siku",
    eggProductionWeekly = "Uzalishaji wa Mayai — Wiki",
    birdInventory = "Hesabu ya Kuku", feedSummary = "Muhtasari wa Chakula",
    quickActions = "Vitendo vya Haraka",
    logEggs = "Ingiza Mayai", addBirds = "Ongeza Kuku",
    addFeed = "Ongeza Chakula", addTask = "Ongeza Kazi",
    upload = "Pakia", download = "Pakua",
    eggsCollected = "Mayai yaliyokusanywa", totalPrefix = "Jumla:",
    totalCost = "Gharama Yote", feedTypes = "Aina za Chakula", lowStock = "Hifadhi Ndogo",
    eggSales = "Mauzo ya Mayai", birdSales = "Mauzo ya Kuku",
    birdsLabel = "Kuku", eggsLabel = "Mayai", tasksLabel = "Kazi", feedLabel = "Chakula",
    syncing = "Inasawazisha...", syncSuccess = "Data imepakiwa!", syncError = "Imeshindwa: ",
    birdInventoryTitle = "Hesabu ya Kuku", addBatch = "Ongeza Kundi",
    noBirds = "Hakuna kuku waliongezwa. Bonyeza + kuongeza kundi lako la kwanza.",
    editBirdBatch = "Hariri Kundi la Kuku", addBirdBatch = "Ongeza Kundi la Kuku",
    breed = "Aina", totalQuantity = "Idadi Yote", pricePerBird = "Bei kwa Kuku",
    birdLeft = "wamebaki", birdSold = "waliouzwa", birdSlaughtered = "waliochinjwa",
    revenuePrefix = "Mapato:",
    eggProductionTitle = "Uzalishaji wa Mayai", noEggs = "Hakuna mayai. Bonyeza + kurekodi uzalishaji.",
    todayProduction = "Uzalishaji wa Leo", eggsUnit = "mayai",
    consumed = "Yaliyotumiwa", remaining = "Yaliyobaki", revenue = "Mapato",
    logEggProduction = "Rekodi Uzalishaji wa Mayai",
    totalEggsCollected = "Jumla ya Mayai Yaliyokusanywa",
    eggsSold = "Mayai Yaliyouzwa", pricePerEgg = "Bei kwa Yai",
    eggsConsumed = "Mayai Yaliyotumiwa",
    feedManagementTitle = "Usimamizi wa Chakula", addFeedLabel = "Ongeza Chakula",
    noFeed = "Hakuna chakula. Bonyeza + kuongeza hesabu ya chakula.",
    feedLowSingular = "aina 1 ya chakula inaisha!", feedLowPlural = "aina %d za chakula zinaisha!",
    lastRestocked = "Imejazwa tena:", lowStockBadge = "HIFADHI NDOGO",
    feedType = "Aina ya Chakula", quantityKg = "Kiasi (kg)",
    lowStockAlertKg = "Tahadhari ya Hifadhi Ndogo (kg)",
    useFeed = "Tumia Chakula", howMuchUsed = "Kiasi gani cha %s kilitumika?",
    tasksTitle = "Kazi", addTaskLabel = "Ongeza Kazi",
    noTasks = "Hakuna kazi bado. Bonyeza + kuongeza kazi.",
    overdue = "Imechelewa · ", due = "Inaisha ",
    editTask = "Hariri Kazi", addTaskTitle = "Ongeza Kazi",
    taskTitle = "Jina la Kazi", dueDate = "Tarehe ya Ukamilishaji",
    healthTitle = "Rekodi za Afya", addRecord = "Ongeza Rekodi",
    noHealth = "Hakuna rekodi za afya. Bonyeza + kurekodi chanjo au dawa.",
    records = "Rekodi", vaccines = "Chanjo", medications = "Dawa",
    typeVaccine = "Chanjo", typeMedication = "Dawa", typeDewormer = "Dawa ya Minyoo",
    typeSupplement = "Kirutubisho", typeOther = "Nyingine",
    nameHint = "Jina (mf. Chanjo ya Newcastle)", date = "Tarehe",
    costOptional = "Gharama (hiari)", dosageOptional = "Kipimo (hiari, mf. 1ml/kuku)",
    birdsTreatedOptional = "Kuku Waliotibiwa (hiari)",
    editHealthRecord = "Hariri Rekodi ya Afya", addHealthRecord = "Ongeza Rekodi ya Afya",
    birdsSuffix = "kuku", dosagePrefix = "Kipimo:", typeLabel = "Aina",
    appTagline = "Usimamizi wa Kuku",
    connectYourFarm = "Unganisha Shamba Lako",
    connectDescription = "Ingiza nambari ya shamba kulandanisha data na timu yako. Watumiaji wote wenye nambari sawa wanaona shamba moja.",
    farmCode = "Nambari ya Shamba", farmCodePlaceholder = "mf. shamba-la-jones-01",
    farmCodeSupporting = "Herufi 3 au zaidi · herufi, nambari, kistari, alama ya chini",
    joinFarm = "Jiunge na Shamba",
    shareCode = "Shiriki nambari hii na kila mtu kwenye shamba lako ili data ilandanishwe.",
)

val EnglishStrings = AppStrings(
    navHome = "Home", navBirds = "Birds", navEggs = "Eggs",
    navFeed = "Feed", navHealth = "Health", navTasks = "Tasks",
    save = "Save", cancel = "Cancel", edit = "Edit", delete = "Delete",
    notesOptional = "Notes (optional)", descriptionOptional = "Description (optional)",
    dashboardTitle = "Farm Dashboard", totalRevenue = "Total Revenue",
    timeRange = "Time Range",
    eggProductionDaily = "Egg Production — Daily",
    eggProductionWeekly = "Egg Production — Weekly",
    birdInventory = "Bird Inventory", feedSummary = "Feed Summary",
    quickActions = "Quick Actions",
    logEggs = "Log Eggs", addBirds = "Add Birds",
    addFeed = "Add Feed", addTask = "Add Task",
    upload = "Upload", download = "Download",
    eggsCollected = "Eggs collected", totalPrefix = "Total:",
    totalCost = "Total Cost", feedTypes = "Feed Types", lowStock = "Low Stock",
    eggSales = "Egg Sales", birdSales = "Bird Sales",
    birdsLabel = "Birds", eggsLabel = "Eggs", tasksLabel = "Tasks", feedLabel = "Feed",
    syncing = "Syncing...", syncSuccess = "All data uploaded!", syncError = "Failed: ",
    birdInventoryTitle = "Bird Inventory", addBatch = "Add Batch",
    noBirds = "No birds added yet. Tap + to add your first batch.",
    editBirdBatch = "Edit Bird Batch", addBirdBatch = "Add Bird Batch",
    breed = "Breed", totalQuantity = "Total Quantity", pricePerBird = "Price per Bird",
    birdLeft = "left", birdSold = "sold", birdSlaughtered = "slaughtered",
    revenuePrefix = "Rev:",
    eggProductionTitle = "Egg Production", noEggs = "No eggs logged. Tap + to log production.",
    todayProduction = "Today's Production", eggsUnit = "eggs",
    consumed = "Consumed", remaining = "Remaining", revenue = "Revenue",
    logEggProduction = "Log Egg Production",
    totalEggsCollected = "Total Eggs Collected",
    eggsSold = "Eggs Sold", pricePerEgg = "Price per Egg",
    eggsConsumed = "Eggs Consumed",
    feedManagementTitle = "Feed Management", addFeedLabel = "Add Feed",
    noFeed = "No feed added yet. Tap + to add feed inventory.",
    feedLowSingular = "1 feed item running low!", feedLowPlural = "%d feed items running low!",
    lastRestocked = "Last restocked:", lowStockBadge = "LOW STOCK",
    feedType = "Feed Type", quantityKg = "Quantity (kg)",
    lowStockAlertKg = "Low Stock Alert (kg)",
    useFeed = "Use Feed", howMuchUsed = "How much %s was used?",
    tasksTitle = "Tasks", addTaskLabel = "Add Task",
    noTasks = "No tasks yet. Tap + to add a task.",
    overdue = "Overdue · ", due = "Due ",
    editTask = "Edit Task", addTaskTitle = "Add Task",
    taskTitle = "Task Title", dueDate = "Due Date",
    healthTitle = "Health Records", addRecord = "Add Record",
    noHealth = "No health records yet. Tap + to log vaccines or medication.",
    records = "Records", vaccines = "Vaccines", medications = "Medications",
    typeVaccine = "Vaccine", typeMedication = "Medication", typeDewormer = "Dewormer",
    typeSupplement = "Supplement", typeOther = "Other",
    nameHint = "Name (e.g. Newcastle Vaccine)", date = "Date",
    costOptional = "Cost (optional)", dosageOptional = "Dosage (optional, e.g. 1ml/bird)",
    birdsTreatedOptional = "Birds Treated (optional)",
    editHealthRecord = "Edit Health Record", addHealthRecord = "Add Health Record",
    birdsSuffix = "birds", dosagePrefix = "Dosage:", typeLabel = "Type",
    appTagline = "Poultry Management",
    connectYourFarm = "Connect your farm",
    connectDescription = "Enter a farm code to sync data with your team. All users sharing the same code see the same farm.",
    farmCode = "Farm Code", farmCodePlaceholder = "e.g. jones-farm-01",
    farmCodeSupporting = "Min 3 characters · letters, numbers, hyphens, underscores",
    joinFarm = "Join Farm",
    shareCode = "Share this code with everyone on your farm to keep data in sync.",
)

val LocalAppStrings = compositionLocalOf { SwahiliStrings }
